import { describe, expect, it } from 'vitest';
import { PIECE_VALUES, chooseMove, createAiPlayer, evaluate, searchBestMove } from '../../src/ai/index.ts';
import {
  applyMove,
  createInitialGameState,
  getAllLegalMoves,
  isInCheck,
  isLegalMove,
  pieceAt,
} from '../../src/engine/index.ts';
import type { GameState, Move } from '../../src/engine/index.ts';
import { position } from '../engine/helpers.ts';

const best = (s: GameState) => {
  const r = chooseMove(s);
  expect(r).not.toBeNull();
  return r!.move;
};
const eq = (m: Move, fx: number, fy: number, tx: number, ty: number) =>
  m.from.x === fx && m.from.y === fy && m.to.x === tx && m.to.y === ty;
/** The move is legal per the engine and moves a piece of the side to move. */
function expectLegal(s: GameState, m: Move) {
  expect(isLegalMove(s, m)).toBe(true);
  expect(pieceAt(s.board, m.from)?.side).toBe(s.turn);
  expect(getAllLegalMoves(s)).toContainEqual(m);
}

describe('AI legality', () => {
  it('always returns a legal move for the side to move (30-ply self-play)', () => {
    let s = createInitialGameState();
    for (let i = 0; i < 30 && s.status === 'playing'; i++) {
      const m = best(s);
      expectLegal(s, m);
      const r = applyMove(s, m);
      expect(r.ok).toBe(true);
      if (!r.ok) return;
      expect(isInCheck(r.state.board, s.turn)).toBe(false); // never leaves own general in check
      s = r.state;
    }
  });

  it('never moves the wrong side', () => {
    const red = createInitialGameState();
    expect(pieceAt(red.board, best(red).from)?.side).toBe('red');
    const blue = position(
      `
      rheakaehr
      .........
      .c.....c.
      p.p.p.p.p
      .........
      ....P....
      P.P...P.P
      .C.....C.
      .........
      RHEAKAEHR`,
      'blue',
    );
    expect(pieceAt(blue.board, best(blue).from)?.side).toBe('blue');
    expect(createAiPlayer('blue').chooseMove(red)).toBeNull(); // not Blue's turn
    expect(createAiPlayer('red').chooseMove(blue)).toBeNull();
  });

  it('respects blocked pieces (rook cannot pass its own pawn to a free rook)', () => {
    const s = position(
      `
      ....k....
      .........
      r........
      p........
      .........
      .........
      R........
      .........
      .........
      ...K.....`,
      'blue',
    );
    const m = best(s);
    expectLegal(s, m);
    expect(eq(m, 0, 2, 0, 6)).toBe(false);
  });

  it('respects the horse-leg block', () => {
    const s = position(
      `
      ....k....
      .........
      ....h....
      ....p....
      .....R...
      .........
      .........
      .........
      .........
      ...K.....`,
      'blue',
    );
    expect(getAllLegalMoves(s).some((m) => eq(m, 4, 2, 5, 4))).toBe(false);
    const m = best(s);
    expectLegal(s, m);
    expect(eq(m, 4, 2, 5, 4)).toBe(false);
  });

  it('respects cannon rules: no capture without a screen, captures with exactly one', () => {
    const noScreen = position(
      `
      ....k....
      .c.......
      .........
      .........
      .........
      .........
      .R.......
      .........
      .........
      ...K.....`,
      'blue',
    );
    const m1 = best(noScreen);
    expectLegal(noScreen, m1);
    expect(eq(m1, 1, 1, 1, 6)).toBe(false);

    const twoScreens = position(
      `
      ....k....
      .c.......
      .........
      .p.......
      .p.......
      .........
      .R.......
      .........
      .........
      ...K.....`,
      'blue',
    );
    const m2 = best(twoScreens);
    expectLegal(twoScreens, m2);
    expect(eq(m2, 1, 1, 1, 6)).toBe(false);

    const oneScreen = position(
      `
      ....k....
      .c.......
      .........
      .p.......
      .........
      .........
      .R.......
      .........
      .........
      ...K.....`,
      'blue',
    );
    expect(eq(best(oneScreen), 1, 1, 1, 6)).toBe(true);
  });

  it('respects palace restrictions', () => {
    const s = position(
      `
      ....k....
      .........
      .....a...
      ......R..
      .........
      .........
      .........
      .........
      .........
      ...K.....`,
      'blue',
    );
    const m = best(s);
    expectLegal(s, m);
    expect(eq(m, 5, 2, 6, 3)).toBe(false);
  });

  it('respects the elephant river restriction', () => {
    const s = position(
      `
      ....k....
      .........
      .........
      .........
      ..e......
      .........
      ....R....
      .........
      .........
      ...K.....`,
      'blue',
    );
    const m = best(s);
    expectLegal(s, m);
    expect(eq(m, 2, 4, 4, 6)).toBe(false);
  });

  it('respects the flying-general rule (pinned blocker on the generals’ file)', () => {
    const s = position(
      `
      ....k....
      .........
      .........
      .........
      .........
      ....h....
      ......R..
      .........
      .........
      ....K....`,
      'blue',
    );
    const m = best(s);
    expectLegal(s, m);
    expect(m.from).not.toEqual({ x: 4, y: 5 }); // any knight move would expose the generals
  });

  it('never leaves its own general in check', () => {
    const s = position(
      `
      ....k....
      .........
      .........
      p.......p
      .........
      ....R....
      .........
      .........
      .........
      ...K.....`,
      'blue',
    );
    expect(s.inCheck).toBe(true);
    const m = best(s);
    const r = applyMove(s, m);
    expect(r.ok && isInCheck(r.state.board, 'blue')).toBe(false);
  });
});

describe('AI decisions', () => {
  it('finds an immediate win (checkmate or stalemate both win in Xiangqi)', () => {
    const s = position(
      `
      .....k...
      .........
      .........
      .........
      .........
      r........
      .........
      .........
      ........r
      ...K.....`,
      'blue',
    );
    const r = applyMove(s, best(s));
    expect(r.ok).toBe(true);
    if (r.ok) {
      expect(['checkmate', 'stalemate']).toContain(r.state.status);
      expect(r.state.winner).toBe('blue');
    }
  });

  it('prefers checkmate when both checkmate and stalemate win', () => {
    // Red to move: R(0,5)→(0,0) mates; R(0,5)→(4,5) would stalemate Blue.
    const s = position(`
      ...k.....
      ........R
      .........
      .........
      .........
      R........
      .........
      .........
      .........
      .....K...`);
    const stalemating = applyMove(s, { from: { x: 0, y: 5 }, to: { x: 4, y: 5 } });
    expect(stalemating.ok && stalemating.state.status).toBe('stalemate'); // both options really exist
    const r = applyMove(s, best(s));
    expect(r.ok && r.state.status).toBe('checkmate');
    expect(r.ok && r.state.winner).toBe('red');
  });

  it('captures a free rook', () => {
    const s = position(
      `
      ....k....
      .........
      r........
      .........
      .........
      .........
      R........
      .........
      .........
      ...K.....`,
      'blue',
    );
    expect(eq(best(s), 0, 2, 0, 6)).toBe(true);
  });

  it('does not blindly capture a defended pawn with its rook', () => {
    const s = position(
      `
      ....k....
      .........
      r........
      .........
      .........
      .........
      P........
      .........
      .........
      R..K.....`,
      'blue',
    );
    const m = best(s);
    expectLegal(s, m);
    expect(eq(m, 0, 2, 0, 6)).toBe(false); // RxP would lose the rook to RxR
  });

  it('prefers the more valuable capture', () => {
    const s = position(
      `
      ....k....
      .........
      .........
      .........
      P..r..R..
      .........
      .........
      .........
      .........
      .....K...`,
      'blue',
    );
    expect(eq(best(s), 3, 4, 6, 4)).toBe(true);
  });

  it('returns null when the game is over', () => {
    const mated = position(
      `
      R..k.....
      ........R
      .........
      .........
      .........
      .........
      .........
      .........
      .........
      .....K...`,
      'blue',
    );
    expect(mated.status).toBe('checkmate');
    expect(searchBestMove(mated)).toBeNull();
  });

  it('is deterministic for the same position', () => {
    const s = createInitialGameState();
    const a = chooseMove(s)!;
    const b = chooseMove(s)!;
    expect(a.move).toEqual(b.move);
    expect(a.score).toBe(b.score);
    expect(a.nodes).toBe(b.nodes);
  });

  it('evaluation is symmetric and uses the material table', () => {
    const s = createInitialGameState();
    expect(evaluate(s, 'red') + evaluate(s, 'blue')).toBe(0);
    expect(Math.abs(evaluate(s, 'red'))).toBe(0);
    expect(PIECE_VALUES).toEqual({
      general: 10000, rook: 900, cannon: 450, knight: 400, elephant: 200, advisor: 200, pawn: 100,
    });
  });

  it('depth 2 is fast from the opening (< 500 ms)', () => {
    const r = chooseMove(createInitialGameState())!;
    expect(r.depth).toBe(2);
    expect(r.timeMs).toBeLessThan(500);
  });

  it('supports depth 3', () => {
    const r = chooseMove(createInitialGameState(), { depth: 3 })!;
    expect(r.depth).toBe(3);
    expect(isLegalMove(createInitialGameState(), r.move)).toBe(true);
  });
});
