import { describe, expect, it } from 'vitest';
import {
  applyMove,
  createGameState,
  createInitialGameState,
  formatBoard,
  generalsFacing,
  getAllLegalMoves,
  getLegalMoves,
  isInCheck,
  isLegalMove,
  parseBoard,
} from '../../src/engine/index.ts';
import { move, position, sq, targets } from './helpers.ts';

const START = `
  rheakaehr
  .........
  .c.....c.
  p.p.p.p.p
  .........
  .........
  P.P.P.P.P
  .C.....C.
  .........
  RHEAKAEHR
`;

describe('initial state', () => {
  it('matches the standard starting position with Red to move', () => {
    const s = createInitialGameState();
    expect(formatBoard(s.board)).toBe(formatBoard(parseBoard(START)));
    expect(s.turn).toBe('red');
    expect(s.status).toBe('playing');
    expect(s.inCheck).toBe(false);
    expect(s.winner).toBeNull();
    expect(s.history).toEqual([]);
  });

  it('gives each side 44 legal opening moves', () => {
    expect(getAllLegalMoves(createInitialGameState())).toHaveLength(44);
    expect(getAllLegalMoves(position(START, 'blue'))).toHaveLength(44);
  });
});

describe('turns and move validation', () => {
  it('switches turns after each legal move', () => {
    let s = createInitialGameState();
    const r1 = applyMove(s, move(1, 7, 4, 7)); // red cannon to centre
    expect(r1.ok).toBe(true);
    if (!r1.ok) return;
    s = r1.state;
    expect(s.turn).toBe('blue');
    const r2 = applyMove(s, move(1, 0, 2, 2)); // blue knight
    expect(r2.ok).toBe(true);
    if (r2.ok) {
      expect(r2.state.turn).toBe('red');
      expect(r2.state.history).toHaveLength(2);
    }
  });

  it('rejects moving the opponent’s piece', () => {
    const s = createInitialGameState();
    const r = applyMove(s, move(1, 2, 1, 3));
    expect(r).toMatchObject({ ok: false, reason: 'wrong_turn' });
    expect(getLegalMoves(s, { x: 1, y: 2 })).toEqual([]);
  });

  it('rejects moving from an empty point', () => {
    expect(applyMove(createInitialGameState(), move(4, 5, 4, 4))).toMatchObject({ ok: false, reason: 'no_piece' });
  });

  it('rejects coordinates off the board', () => {
    const s = createInitialGameState();
    expect(applyMove(s, move(0, 9, 0, 10))).toMatchObject({ ok: false, reason: 'invalid_coordinate' });
    expect(applyMove(s, move(-1, 9, 0, 9))).toMatchObject({ ok: false, reason: 'invalid_coordinate' });
    expect(getLegalMoves(s, { x: 9, y: 0 })).toEqual([]);
  });

  it('rejects illegal moves and returns the state unchanged', () => {
    const s = createInitialGameState();
    const r = applyMove(s, move(0, 9, 1, 8)); // rook diagonally
    expect(r).toMatchObject({ ok: false, reason: 'illegal_move' });
    expect(r.state).toBe(s);
  });

  it('does not mutate the previous state', () => {
    const s = createInitialGameState();
    const before = formatBoard(s.board);
    applyMove(s, move(0, 9, 0, 8));
    expect(formatBoard(s.board)).toBe(before);
    expect(s.turn).toBe('red');
  });
});

describe('captures', () => {
  it('removes the captured piece and records it', () => {
    const s = createInitialGameState();
    const r = applyMove(s, move(1, 7, 1, 0)); // cannon takes knight over the screen
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    expect(r.captured).toEqual({ side: 'blue', type: 'knight' });
    expect(r.move).toMatchObject({ piece: { side: 'red', type: 'cannon' }, captured: { side: 'blue', type: 'knight' } });
    expect(r.state.board[1]![0]).toEqual({ side: 'red', type: 'cannon' });
    const count = r.state.board.flat().filter(Boolean).length;
    expect(count).toBe(31);
  });

  it('cannot capture own pieces', () => {
    expect(isLegalMove(createInitialGameState(), move(0, 9, 0, 6))).toBe(false);
  });
});

describe('check', () => {
  it('detects a check delivered by a move', () => {
    const s = position(`
      ....k....
      .........
      .........
      .........
      .........
      R........
      .........
      .........
      .........
      ...K.....
    `);
    const r = applyMove(s, move(0, 5, 4, 5));
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    expect(r.check).toBe(true);
    expect(r.state.inCheck).toBe(true);
    expect(r.state.turn).toBe('blue');
    expect(r.state.status).toBe('playing');
  });

  it('only allows moves that resolve check', () => {
    const s = position(
      `
      ....k....
      .........
      .........
      p........
      .........
      ....R....
      .........
      .........
      .........
      ...K.....
    `,
      'blue',
    );
    expect(s.inCheck).toBe(true);
    // Moving an unrelated pawn does not resolve the check.
    expect(applyMove(s, move(0, 3, 0, 4))).toMatchObject({ ok: false, reason: 'illegal_move' });
    // (3,0) would face the red general on file 3; (4,1) stays on the rook's file.
    expect(targets(s, 4, 0)).toEqual(sq([5, 0]));
    for (const m of getAllLegalMoves(s)) {
      const r = applyMove(s, m);
      expect(r.ok).toBe(true);
      if (r.ok) expect(isInCheck(r.state.board, 'blue')).toBe(false);
    }
  });

  it('allows blocking or capturing the checking piece', () => {
    const s = position(
      `
      ....k....
      .........
      .........
      .........
      r........
      ....R....
      .........
      .........
      .........
      ...K.....
    `,
      'blue',
    );
    const t = targets(s, 0, 4);
    expect(t).toContain('4,4'); // block
    expect(t).not.toContain('0,3'); // does not resolve check
  });

  it('a pinned piece cannot expose its general', () => {
    const s = position(
      `
      ....k....
      .........
      ....r....
      .........
      .........
      ....R....
      .........
      .........
      .........
      ...K.....
    `,
      'blue',
    );
    expect(s.inCheck).toBe(false);
    // The blue rook may slide along the file (or capture) but not leave it.
    expect(targets(s, 4, 2)).toEqual(sq([4, 1], [4, 3], [4, 4], [4, 5]));
  });

  it('detects checks from knights and cannons', () => {
    const knight = position(`
      ....k....
      .........
      ...H.....
      .........
      .........
      .........
      .........
      .........
      .........
      ...K.....
    `, 'blue');
    expect(knight.inCheck).toBe(true);

    const cannon = position(`
      ....k....
      .........
      ....p....
      .........
      ....C....
      .........
      .........
      .........
      .........
      ...K.....
    `, 'blue');
    expect(cannon.inCheck).toBe(true);
  });
});

describe('flying generals', () => {
  it('detects generals facing on an open file', () => {
    expect(generalsFacing(parseBoard(`
      ....k....
      .........
      .........
      .........
      .........
      .........
      .........
      .........
      .........
      ....K....
    `))).toBe(true);
    expect(generalsFacing(createInitialGameState().board)).toBe(false);
  });

  it('a lone blocker between the generals cannot leave the file', () => {
    const s = position(`
      ....k....
      .........
      .........
      .........
      .........
      ....R....
      .........
      .........
      .........
      ....K....
    `);
    const t = targets(s, 4, 5);
    expect(t.every((p) => p.startsWith('4,'))).toBe(true);
    expect(t).toContain('4,0'); // may capture the general's file-mate
    expect(isLegalMove(s, move(4, 5, 0, 5))).toBe(false);
  });

  it('opening the file by moving the only blocking pawn is illegal', () => {
    const s = position(`
      ....k....
      .........
      .........
      .........
      ....P....
      .........
      .........
      .........
      .........
      ....K....
    `);
    // After crossing the river the pawn could step sideways, but that opens the file.
    expect(targets(s, 4, 4)).toEqual(sq([4, 3]));
  });
});

describe('checkmate and stalemate', () => {
  it('detects checkmate (double rook)', () => {
    const s = position(
      `
      R..k.....
      ........R
      .........
      .........
      .........
      .........
      .........
      .........
      .........
      .....K...
    `,
      'blue',
    );
    expect(s.inCheck).toBe(true);
    expect(s.status).toBe('checkmate');
    expect(s.winner).toBe('red');
    expect(getAllLegalMoves(s)).toEqual([]);
  });

  it('a mating move ends the game', () => {
    const s = position(`
      ...k.....
      ........R
      .........
      .........
      .........
      R........
      .........
      .........
      .........
      .....K...
    `);
    const r = applyMove(s, move(0, 5, 0, 0));
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    expect(r.state.status).toBe('checkmate');
    expect(r.state.winner).toBe('red');
    expect(applyMove(r.state, move(3, 0, 4, 0))).toMatchObject({ ok: false, reason: 'game_over' });
    expect(getLegalMoves(r.state, { x: 3, y: 0 })).toEqual([]);
  });

  it('detects checkmate by double cannon (screen rule)', () => {
    // Cannon (4,6) checks over the screen cannon (4,5). Blocking on (4,1) with an
    // advisor gives cannon (4,5) a screen instead; stepping to (4,1) is still in check.
    const s = position(
      `
      ...aka...
      .........
      .........
      .........
      .........
      ....C....
      ....C....
      .........
      .........
      ...K.....
    `,
      'blue',
    );
    expect(s.inCheck).toBe(true);
    expect(s.status).toBe('checkmate');
    expect(s.winner).toBe('red');
  });

  it('detects stalemate (no legal move, not in check) as a loss', () => {
    const s = position(
      `
      ....k....
      ........R
      .........
      .........
      .........
      ...R.R...
      .........
      .........
      .........
      ...K.....
    `,
      'blue',
    );
    expect(s.inCheck).toBe(false);
    expect(s.status).toBe('stalemate');
    expect(s.winner).toBe('red');
  });
});

describe('general capture', () => {
  it('ends the game when a general is captured (non-standard position)', () => {
    const s = position(
      `
      ...k.....
      .........
      .........
      .........
      .........
      ....r....
      .........
      .........
      .........
      ....K....
    `,
      'blue',
    );
    const r = applyMove(s, move(4, 5, 4, 9));
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    expect(r.state.status).toBe('general_captured');
    expect(r.state.winner).toBe('blue');
  });

  it('a board without a general is game over', () => {
    const s = createGameState(parseBoard(`
      ...k.....
      .........
      .........
      .........
      .........
      .........
      .........
      .........
      .........
      ....R....
    `), 'red');
    expect(s.status).toBe('general_captured');
    expect(s.winner).toBe('blue');
  });
});

describe('notation helpers', () => {
  it('round-trips a diagram', () => {
    expect(formatBoard(parseBoard(START))).toBe(START.trim().split('\n').map((r) => r.trim()).join('\n'));
  });

  it('rejects malformed diagrams', () => {
    expect(() => parseBoard('...')).toThrow();
    expect(() => parseBoard(START.replace('rheakaehr', 'rheakaehx'))).toThrow(/Unknown piece/);
  });
});
