import { describe, expect, it } from 'vitest';
import { applyMove, isLegalMove } from '../../src/engine/index.ts';
import { move, position, sq, targets } from './helpers.ts';

describe('rook', () => {
  const open = position(`
    ...k.....
    .........
    .........
    .........
    .........
    ....R....
    .........
    .........
    .........
    .....K...
  `);

  it('moves horizontally along its rank', () => {
    const t = targets(open, 4, 5);
    for (let x = 0; x <= 8; x++) if (x !== 4) expect(t).toContain(`${x},5`);
  });

  it('moves vertically along its file', () => {
    const t = targets(open, 4, 5);
    for (let y = 0; y <= 9; y++) if (y !== 5) expect(t).toContain(`4,${y}`);
    expect(t).toHaveLength(17);
  });

  it('is blocked by pieces and cannot jump', () => {
    const s = position(`
      ...k.....
      .........
      .........
      ....P....
      .........
      ....R.p..
      .........
      .........
      .........
      .....K...
    `);
    const t = targets(s, 4, 5);
    expect(t).toContain('4,4');
    expect(t).not.toContain('4,3'); // own piece
    expect(t).not.toContain('4,2'); // behind own piece
    expect(t).not.toContain('7,5'); // behind enemy piece
  });

  it('captures the first enemy piece in line', () => {
    const s = position(`
      ...k.....
      .........
      .........
      .........
      .........
      ....R.p..
      .........
      .........
      .........
      .....K...
    `);
    expect(targets(s, 4, 5)).toContain('6,5');
    const r = applyMove(s, move(4, 5, 6, 5));
    expect(r.ok).toBe(true);
    if (r.ok) {
      expect(r.captured).toEqual({ side: 'blue', type: 'pawn' });
      expect(r.state.board[6]![5]).toEqual({ side: 'red', type: 'rook' });
      expect(r.state.board[4]![5]).toBeNull();
    }
  });
});

describe('knight', () => {
  const open = position(`
    ...k.....
    .........
    .........
    .........
    .........
    ....H....
    .........
    .........
    .........
    .....K...
  `);

  it('moves in all eight L shapes', () => {
    expect(targets(open, 4, 5)).toEqual(sq([5, 3], [3, 3], [6, 4], [6, 6], [5, 7], [3, 7], [2, 4], [2, 6]));
  });

  it('is blocked by a piece on the horse leg (either side)', () => {
    const s = position(`
      ...k.....
      .........
      .........
      .........
      ....P....
      ....Hp...
      .........
      .........
      .........
      .....K...
    `);
    // Leg up (4,4) blocked by own pawn → (3,3), (5,3) illegal.
    // Leg right (5,5) blocked by enemy pawn → (6,4), (6,6) illegal.
    expect(targets(s, 4, 5)).toEqual(sq([5, 7], [3, 7], [2, 4], [2, 6]));
    expect(isLegalMove(s, move(4, 5, 5, 3))).toBe(false);
    expect(isLegalMove(s, move(4, 5, 6, 4))).toBe(false);
  });

  it('captures enemies but not own pieces', () => {
    const s = position(`
      ...k.....
      .........
      .........
      .........
      ..P......
      ....H....
      ......p..
      .........
      .........
      .....K...
    `);
    const t = targets(s, 4, 5);
    expect(t).toContain('6,6');
    expect(t).not.toContain('2,4');
    const r = applyMove(s, move(4, 5, 6, 6));
    expect(r.ok && r.captured).toEqual({ side: 'blue', type: 'pawn' });
  });

  it('starting knight has two moves', () => {
    const s = position(`
      rheakaehr
      .........
      .c.....c.
      p.p.p.p.p
      .........
      .........
      P.P.P.P.P
      .C.....C.
      .........
      RHEAKAEHR
    `);
    expect(targets(s, 1, 9)).toEqual(sq([0, 7], [2, 7]));
  });
});

describe('elephant', () => {
  it('moves exactly two points diagonally', () => {
    const s = position(`
      ...k.....
      .........
      .........
      .........
      .........
      .........
      .........
      ....E....
      .........
      .....K...
    `);
    expect(targets(s, 4, 7)).toEqual(sq([2, 5], [6, 5], [2, 9], [6, 9]));
  });

  it('is blocked when the elephant eye is occupied', () => {
    const s = position(`
      ...k.....
      .........
      .........
      .........
      .........
      .........
      .........
      .........
      ...p.....
      ..E..K...
    `);
    expect(targets(s, 2, 9)).toEqual(sq([0, 7]));
  });

  it('cannot cross the river (red)', () => {
    const s = position(`
      ...k.....
      .........
      .........
      .........
      .........
      ..E......
      .........
      .........
      .........
      .....K...
    `);
    expect(targets(s, 2, 5)).toEqual(sq([0, 7], [4, 7]));
    expect(isLegalMove(s, move(2, 5, 4, 3))).toBe(false);
  });

  it('cannot cross the river (blue)', () => {
    const s = position(
      `
      ...k.....
      .........
      .........
      .........
      ..e......
      .........
      .........
      .........
      .........
      .....K...
    `,
      'blue',
    );
    expect(targets(s, 2, 4)).toEqual(sq([0, 2], [4, 2]));
  });
});

describe('advisor', () => {
  it('moves one point diagonally', () => {
    const s = position(`
      ...k.....
      .........
      .........
      .........
      .........
      .........
      .........
      .........
      ....A....
      ....K....
    `);
    expect(targets(s, 4, 8)).toEqual(sq([3, 7], [5, 7], [3, 9], [5, 9]));
  });

  it('must stay inside its palace', () => {
    const s = position(`
      ...k.....
      .........
      .........
      .........
      .........
      .........
      .........
      .....A...
      .........
      ....K....
    `);
    expect(targets(s, 5, 7)).toEqual(sq([4, 8]));
    expect(isLegalMove(s, move(5, 7, 6, 6))).toBe(false);
    expect(isLegalMove(s, move(5, 7, 4, 6))).toBe(false);
  });

  it('blue advisor stays in the blue palace', () => {
    const s = position(
      `
      ...ka....
      .........
      .........
      .........
      .........
      .........
      .........
      .........
      .........
      .....K...
    `,
      'blue',
    );
    expect(targets(s, 4, 0)).toEqual(sq([3, 1], [5, 1]));
  });
});

describe('general', () => {
  it('moves one point orthogonally', () => {
    const s = position(`
      ....k....
      .........
      .........
      .........
      .........
      ....P....
      .........
      .........
      ....K....
      .........
    `);
    expect(targets(s, 4, 8)).toEqual(sq([4, 7], [4, 9], [3, 8], [5, 8]));
    expect(isLegalMove(s, move(4, 8, 3, 7))).toBe(false); // no diagonal
  });

  it('must stay inside its palace', () => {
    const s = position(`
      ....k....
      .........
      .........
      .........
      .........
      ....P....
      .........
      ...K.....
      .........
      .........
    `);
    expect(targets(s, 3, 7)).toEqual(sq([4, 7], [3, 8]));
    expect(isLegalMove(s, move(3, 7, 3, 6))).toBe(false);
    expect(isLegalMove(s, move(3, 7, 2, 7))).toBe(false);
  });

  it('cannot move onto an open file facing the enemy general (flying general)', () => {
    const s = position(`
      ....k....
      .........
      .........
      .........
      .........
      .........
      .........
      .........
      .........
      ...K.....
    `);
    expect(isLegalMove(s, move(3, 9, 4, 9))).toBe(false);
    expect(targets(s, 3, 9)).toEqual(sq([3, 8]));
  });
});

describe('cannon', () => {
  it('moves like a rook when not capturing', () => {
    const s = position(`
      ...k.....
      .........
      .........
      .........
      .........
      ....C....
      .........
      .........
      .........
      .....K...
    `);
    expect(targets(s, 4, 5)).toHaveLength(17);
  });

  it('cannot jump a screen to an empty point', () => {
    const s = position(`
      ...k.....
      .........
      .........
      ....P....
      .........
      ....C....
      .........
      .........
      .........
      .....K...
    `);
    const t = targets(s, 4, 5);
    expect(t).toContain('4,4');
    expect(t).not.toContain('4,3');
    expect(t).not.toContain('4,2');
    expect(t).not.toContain('4,1');
  });

  it('captures with exactly one screen', () => {
    const s = position(`
      ...k.....
      ....p....
      .........
      ....P....
      .........
      ....C....
      .........
      .........
      .........
      .....K...
    `);
    expect(targets(s, 4, 5)).toContain('4,1');
    const r = applyMove(s, move(4, 5, 4, 1));
    expect(r.ok && r.captured).toEqual({ side: 'blue', type: 'pawn' });
  });

  it('cannot capture with zero screens', () => {
    const s = position(`
      ...k.....
      .........
      .........
      .........
      .........
      ....C.p..
      .........
      .........
      .........
      .....K...
    `);
    const t = targets(s, 4, 5);
    expect(t).toContain('5,5');
    expect(t).not.toContain('6,5');
    expect(t).not.toContain('7,5');
  });

  it('cannot capture with two screens', () => {
    const s = position(`
      ...k.....
      ....p....
      ....p....
      ....P....
      .........
      ....C....
      .........
      .........
      .........
      .....K...
    `);
    const t = targets(s, 4, 5);
    expect(t).toContain('4,2'); // one screen (4,3)
    expect(t).not.toContain('4,1'); // two screens (4,3), (4,2)
  });

  it('cannot capture its own piece over a screen', () => {
    const s = position(`
      ...k.....
      ....P....
      .........
      ....p....
      .........
      ....C....
      .........
      .........
      .........
      .....K...
    `);
    expect(targets(s, 4, 5)).not.toContain('4,1');
  });

  it('can capture the knight over the screen from the starting position', () => {
    const s = position(`
      rheakaehr
      .........
      .c.....c.
      p.p.p.p.p
      .........
      .........
      P.P.P.P.P
      .C.....C.
      .........
      RHEAKAEHR
    `);
    expect(targets(s, 1, 7)).toContain('1,0');
    expect(targets(s, 1, 7)).not.toContain('1,2');
  });
});

describe('pawn', () => {
  it('moves only forward before crossing the river (red)', () => {
    const s = position(`
      ...k.....
      .........
      .........
      .........
      .........
      .........
      ....P....
      .........
      .........
      .....K...
    `);
    expect(targets(s, 4, 6)).toEqual(sq([4, 5]));
  });

  it('moves only forward before crossing the river (blue)', () => {
    const s = position(
      `
      ...k.....
      .........
      .........
      ....p....
      .........
      .........
      .........
      .........
      .........
      .....K...
    `,
      'blue',
    );
    expect(targets(s, 4, 3)).toEqual(sq([4, 4]));
  });

  it('may also move sideways after crossing the river', () => {
    const red = position(`
      ...k.....
      .........
      .........
      .........
      ....P....
      .........
      .........
      .........
      .........
      .....K...
    `);
    expect(targets(red, 4, 4)).toEqual(sq([4, 3], [3, 4], [5, 4]));

    const blue = position(
      `
      ...k.....
      .........
      .........
      .........
      .........
      .........
      ....p....
      .........
      .........
      .....K...
    `,
      'blue',
    );
    expect(targets(blue, 4, 6)).toEqual(sq([4, 7], [3, 6], [5, 6]));
  });

  it('never moves backward', () => {
    const s = position(`
      ...k.....
      .........
      .........
      .........
      ....P....
      .........
      .........
      .........
      .........
      .....K...
    `);
    expect(isLegalMove(s, move(4, 4, 4, 5))).toBe(false);
    const r = applyMove(s, move(4, 4, 4, 5));
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.reason).toBe('illegal_move');
  });

  it('on the last rank only moves sideways', () => {
    const s = position(`
      ...k..P..
      .........
      .........
      .........
      .........
      .........
      .........
      .........
      .........
      .....K...
    `);
    expect(targets(s, 6, 0)).toEqual(sq([5, 0], [7, 0]));
  });

  it('respects the board edge', () => {
    const s = position(`
      ...k.....
      .........
      .........
      P........
      .........
      .........
      .........
      .........
      .........
      .....K...
    `);
    expect(targets(s, 0, 3)).toEqual(sq([0, 2], [1, 3]));
  });
});
